name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Don't run on forks
    if: github.repository == 'antithrow/antithrow'
    # TODO: Trusted publishing requires npm@11.5.1, but ubuntu-latest currently ships with
    # npm@10.8.2. ubuntu-slim is slightly newer, shipping with npm@11.6.2
    runs-on: ubuntu-slim
    permissions:
      contents: write # To create releases
      id-token: write # OIDC trusted publishing
      pull-requests: write # Create changeset pull request

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Bun.sh
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

      - name: Install dependencies
        run: bun install

      - name: Run changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: bun release
